'NoneType' object is not callable网络连接失败 2017-03-25 06:56:34,600 stats.py[line:108]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 08:53:09,249 stats.py[line:110]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 08:54:42,143 stats.py[line:110]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:00:17,209 stats.py[line:112]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:00:23,198 stats.py[line:112]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:00:25,202 stats.py[line:112]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:00:27,285 stats.py[line:112]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:00:29,236 stats.py[line:112]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:00:31,312 stats.py[line:112]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:00:33,328 stats.py[line:112]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:07:28,072 stats.py[line:113]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:09:10,538 stats.py[line:113]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:11:05,730 stats.py[line:113]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:13:20,935 stats.py[line:111]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:13:52,703 stats.py[line:111]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:17:44,657 stats.py[line:112]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:18:34,138 stats.py[line:111]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:24:26,345 stats.py[line:111]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:24:47,915 stats.py[line:111]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:24:54,162 stats.py[line:111]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:24:56,031 stats.py[line:111]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:24:57,959 stats.py[line:111]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:24:59,999 stats.py[line:111]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:25:01,956 stats.py[line:111]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:25:04,041 stats.py[line:111]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:27:02,762 stats.py[line:112]                      WARNING 
'NoneType' object is not callable网络连接失败 2017-03-25 09:27:08,936 stats.py[line:112]                      WARNING 
